### ISSUE TITLE
400 Bad Content-Type header

### ISSUE THREAD

**Issue by Kiljax** [graphaware/neo4j-php-client#142]
I've previously never had problems setting up neo4j with the graphaware client, but I am now receiving the following error message when trying to do anything with the connection.

Error:

:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST http://neo4j:***@172.16.1.12:7474/db/data/transaction/commit` resulted in a `400 Bad Content-Type header value: ''` response in /var/www/html/SCDB/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/html/SCDB/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/html/SCDB/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/SCDB/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/html/SCDB/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/SCDB/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)

Connector Code:

require_once '//var/www/html/SCDB/vendor/autoload.php';
use GraphAware\Neo4j\Client\ClientBuilder;

Connector call:

function buildCon()
{
$client = ClientBuilder::create()

    ->addConnection('default', 'http://neo4j:*****!@IPADDRESS:7474') // Example for HTTP connection configuration (port is optional)
->addConnection('bolt', 'bolt://neo4j:*****!@IPADDRESS:7687')
->build();
return $client;
}

Basic Call:

$session = buildCon();
$query = $session->run("MATCH (f:Fleet)
return f.Name as Name");
$results = $query->getRecords();

Server configuration:

Ubuntu 16.04

Neo4j Server version: 3.4.9 (enterprise)

Composer installed via method found at: https://github.com/graphaware/neo4j-php-client

composer require graphaware/neo4j-php-client:^4.0

PHP -v:

PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS ) Copyright (c) 1997-2017 The PHP Group Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies with Zend OPcache v7.0.32-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

Apache2 -v: Server version: Apache/2.4.18 (Ubuntu) Server built: 2018-06-07T19:43:03

I'm not entirely sure what has changed, but this almost exact code is still working on a project I have that is currently live. Any assistance in the matter would be greatly appreciated

**Comment by Maskman24610** [comment]
I think the bug may be due to Apache/2.4，you can try Apache 2.2 or nginx

**Comment by pkutum** [comment]
It is working fine with Apache 2.4.18, neo4j-3.3.3 and php 7.1
But giving above error when working with Apache 2.4.41, neo4j 3.5.8 and php 7.2

Tried above solution by using nginx but it did not work, still getting same error.

Somebody suggested downgrading php to 7.1 to make it work.

neo4j-php-client version is same on both machines.

What could be the error? Please help, I am stuck on this since long.

**Comment by CryHenry** [comment]
For us, we found Curl Wasn't installed. Once we installed that package, all went well :)

**Comment by pkutum** [comment]
Thank you very much @CryHenry . I was waiting on it for so many months and could not update neo4j.
It worked for me. Amazing how could you figure this out.

Here is what I did based on above:
$ sudo apt install  php-curl
$ sudo service php-fpm restart
