### ISSUE TITLE
Issue with MessageTrait

### ISSUE THREAD

**Issue by GameCharmer** [graphaware/neo4j-php-client#144]
I seem to be running into a weird error right out of the gate trying to get this working.  I'm able to use the neo4j browser fine, so I know it's up and functional.  I can run `CREATE (n:Member)` in the browser and it works fine, but when I try to do so via the client, I get the below error.  I've tried with and without the bolt connection and still produce the same results.  I'm running this via CLI.

```php
<?php
require('../vendor/autoload.php');

$cClient = \GraphAware\Neo4j\Client\ClientBuilder::create()
    ->addConnection('default','http://127.0.0.1:7474')
    ->build();
$cClient->run('CREATE (n:Member)');

```

```
PHP Fatal error:  Uncaught TypeError: trim() expects parameter 1 to be string, boolean given in /var/www/vendor/nyholm/psr7/src/MessageTrait.php:215
Stack trace:
#0 /var/www/vendor/nyholm/psr7/src/MessageTrait.php(215): trim(true, ' \t')
#1 [internal function]: Nyholm\Psr7\Request->Nyholm\Psr7\{closure}(true)
#2 /var/www/vendor/nyholm/psr7/src/MessageTrait.php(216): array_map(Object(Closure), Array)
#3 /var/www/vendor/nyholm/psr7/src/MessageTrait.php(186): Nyholm\Psr7\Request->trimHeaderValues(Array)
#4 /var/www/vendor/nyholm/psr7/src/Request.php(50): Nyholm\Psr7\Request->setHeaders(Array)
#5 /var/www/vendor/nyholm/psr7/src/Factory/MessageFactory.php(24): Nyholm\Psr7\Request->__construct('POST', Object(Nyholm\Psr7\Uri), Array, '{"statements":[...', '1.1')
#6 /var/www/vendor/graphaware/neo4j-php-client/src/HttpDriver/Session.php(203): Nyholm\Psr7\Factory\MessageFactory->createRequest('POST', 'http://127.0.0....', Array, '{"statements":[...')
#7 /var/www/vendor/graphaware/neo4j-php-client/src/HttpDriver/Session.php(146): GraphAw in /var/www/vendor/nyholm/psr7/src/MessageTrait.php on line 215
```

**Comment by ikwattro** [comment]
@Nyholm

**Comment by GameCharmer** [comment]
I completely forgot to include my composer & OS info.  I'm in Ubuntu 16.04.5. In the composer.json, I have `"graphaware/neo4j-php-client": "^4.0",` in require, and in composer.lock (limited to graphaware items)
```
        {
            "name": "graphaware/neo4j-bolt",
            "version": "1.11.0",
            "source": {
                "type": "git",
                "url": "https://github.com/graphaware/neo4j-bolt-php.git",
                "reference": "c4fdfc5b4ed52fe409926395a10a22d860ad31ed"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/graphaware/neo4j-bolt-php/zipball/c4fdfc5b4ed52fe409926395a10a22d860ad31ed",
                "reference": "c4fdfc5b4ed52fe409926395a10a22d860ad31ed",
                "shasum": ""
            },
            "require": {
                "ext-bcmath": "*",
                "ext-mbstring": "*",
                "graphaware/neo4j-common": "^3.4",
                "myclabs/php-enum": "^1.4",
                "php": ">= 5.6",
                "symfony/event-dispatcher": "^2.7|^3.0|^4.0"
            },
            "require-dev": {
                "behat/behat": "~3.0.4",
                "phpunit/phpunit": "^4.8",
                "symfony/stopwatch": "^2.7"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "GraphAware\\Bolt\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Christophe Willemsen",
                    "email": "christophe@graphaware.com"
                }
            ],
            "description": "Neo4j Bolt Binary Protocol PHP Driver",
            "time": "2017-12-12T08:26:08+00:00"
        },
        {
            "name": "graphaware/neo4j-common",
            "version": "3.5.0",
            "source": {
                "type": "git",
                "url": "https://github.com/graphaware/neo4j-php-commons.git",
                "reference": "a1aef65e3275c006a9c91ca8be7d800e8391b514"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/graphaware/neo4j-php-commons/zipball/a1aef65e3275c006a9c91ca8be7d800e8391b514",
                "reference": "a1aef65e3275c006a9c91ca8be7d800e8391b514",
                "shasum": ""
            },
            "require": {
                "myclabs/php-enum": "^1.4"
            },
            "require-dev": {
                "phpunit/phpunit": "^4.0"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "GraphAware\\Common\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "ApacheV2"
            ],
            "authors": [
                {
                    "name": "Christophe Willemsen",
                    "email": "christophe@graphaware.com"
                }
            ],
            "description": "Common Utilities library for Neo4j",
            "keywords": [
                "cypher",
                "database",
                "graph",
                "neo4j",
                "statement"
            ],
            "time": "2017-06-08T21:29:20+00:00"
        },
        {
            "name": "graphaware/neo4j-php-client",
            "version": "4.8.4",
            "source": {
                "type": "git",
                "url": "https://github.com/graphaware/neo4j-php-client.git",
                "reference": "47b9b97114db8b81bd1c8df50a44f1369ae9748b"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/graphaware/neo4j-php-client/zipball/47b9b97114db8b81bd1c8df50a44f1369ae9748b",
                "reference": "47b9b97114db8b81bd1c8df50a44f1369ae9748b",
                "shasum": ""
            },
            "require": {
                "ext-bcmath": "*",
                "ext-mbstring": "*",
                "graphaware/neo4j-bolt": "^1.5",
                "graphaware/neo4j-common": "^3.4",
                "myclabs/php-enum": "^1.4",
                "php": "^5.6 || ^7.0",
                "php-http/client-common": "^1.0",
                "php-http/discovery": "^1.0",
                "php-http/guzzle6-adapter": "^1.0",
                "php-http/httplug": "^1.0",
                "php-http/message": "^1.0",
                "php-http/message-factory": "^1.0",
                "symfony/event-dispatcher": "^2.7 || ^3.0 || ^4.0"
            },
            "require-dev": {
                "friendsofphp/php-cs-fixer": "^2.0",
                "phpunit/phpunit": "^4.0",
                "symfony/stopwatch": "^3.0"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "GraphAware\\Neo4j\\Client\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Christophe Willemsen",
                    "email": "christophe@graphaware.com"
                }
            ],
            "description": "Neo4j-PHP-Client is the most advanced PHP Client for Neo4j",
            "homepage": "http://graphaware.com",
            "keywords": [
                "bolt",
                "client",
                "cluster",
                "database",
                "graph",
                "high-availability",
                "http",
                "neo4j"
            ],
            "time": "2018-01-11T16:48:38+00:00"
        },
```

Installed version of neo4j is 3.4.9.  I ran checks against neo4j, neo4j-admin, and neo4j-shell just to make sure everything lined up
```
$ neo4j --version
neo4j 3.4.9
$ neo4j-admin --version
neo4j-admin 3.4.9
$ neo4j-shell --version
Neo4j Community, version 3.4.9
```

Let me know if there's any more info I can provide.

**Comment by yassir3wad** [comment]
+1
