### ISSUE TITLE
why neo4j to PHP can't gat DB

### ISSUE THREAD

**Issue by leosample** [graphaware/neo4j-php-client#146]
composer.json
{
    "require": {
		"neoxygen/neoclient": "^3.3",
        "graphaware/neo4j-php-client": "^4.0"
    }
}

PHP 
<?php

echo "hello php neo4j 2</br>";

require_once 'vendor/autoload.php';

use GraphAware\Neo4j\Client\ClientBuilder;

$client = ClientBuilder::create()
    ->addConnection('default', 'http://neo4j:neo4j@127.0.0.1:7474') // Example for HTTP connection configuration (port is optional)
    ->addConnection('bolt', 'bolt://neo4j:neo4j@127.0.0.1:7687') // Example for BOLT connection configuration (port is optional)
    ->build();

$client -> run('MATCH(n:AAA) RETURN n');

echo "123456</br>";
?>
ERROR

Fatal error: Uncaught Http\Client\Common\Exception\ClientErrorException: Bad Content-Type header value: '' in C:\Apache24\htdocs\sampletsspd\vendor\php-http\client-common\src\Plugin\ErrorPlugin.php:72 Stack trace: #0 C:\Apache24\htdocs\sampletsspd\vendor\php-http\client-common\src\Plugin\ErrorPlugin.php(54): Http\Client\Common\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\Apache24\htdocs\sampletsspd\vendor\php-http\httplug\src\Promise\HttpFulfilledPromise.php(34): Http\Client\Common\Plugin\ErrorPlugin->Http\Client\Common\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\Apache24\htdocs\sampletsspd\vendor\php-http\client-common\src\Plugin\ErrorPlugin.php(55): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure)) #3 C:\Apache24\htdocs\sampletsspd\vendor\php-http\client-common\src\PluginClient.php(160): Http\Client\Common\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure)) #4 C:\Apache in C:\Apache24\htdocs\sampletsspd\vendor\php-http\client-common\src\Plugin\ErrorPlugin.php on line 72

**Comment by mryamac** [comment]
I got same error and fixed by removing 
`->addConnection('default', 'http://neo4j:neo4j@127.0.0.1:7474')`
Then what I have:
`$client = ClientBuilder::create()`
`->addConnection('bolt', 'bolt://neo4j:neo4j@127.0.0.1:7687'`
`->build(); `

**Comment by pkutum** [comment]
Try installing php-curl module (as mentioned here: https://github.com/graphaware/neo4j-php-client/issues/142#issuecomment-558857861 )
